# Generated by Django 5.2.14 on 2026-05-25 15:44

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('member_subject_mode', models.CharField(choices=[('self', 'Eigene Person ist Mitglied'), ('via_associate', 'Mitglied ist eine andere Person')], default='self', help_text='self: Wer sich registriert, IST das Mitglied (VHS-Kurs, Förderverein). via_associate: Wer sich registriert, meldet jemand anderen an (Schulklasse).', max_length=20, verbose_name='Mitglieder-Modus')),
                ('relationship_roles', models.JSONField(blank=True, default=list, help_text='Liste von Rollen für PersonRelationship, z.B. ["Mutter von", "Vater von", "Erziehungsberechtigte von"].', verbose_name='Beziehungsrollen')),
                ('default_record_role', models.CharField(choices=[('member', 'Mitglied'), ('associate', 'Zugeordnet')], default='member', max_length=20, verbose_name='Default-Rolle für neue Einträge')),
                ('display_default', models.JSONField(blank=True, default=dict, help_text='Welche Attribute werden per Default in der Listenansicht angezeigt (Phase 3a).', verbose_name='Default-Anzeige')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Listen-Vorlage',
                'verbose_name_plural': 'Listen-Vorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('email_alias', models.CharField(help_text="Local-Part der Listen-Adresse, z.B. '5a' für 5a@<MAIL_DOMAIN>.", max_length=100, unique=True, verbose_name='E-Mail-Alias')),
                ('visibility', models.CharField(choices=[('public_visible', 'öffentlich sichtbar'), ('public_editable', 'öffentlich bearbeitbar'), ('private', 'privat')], default='private', max_length=20, verbose_name='Sichtbarkeit')),
                ('cohort_grade', models.PositiveSmallIntegerField(blank=True, help_text='5–12. Nur für Schulklassen-Vorlagen.', null=True, verbose_name='Klassenstufe')),
                ('cohort_track', models.CharField(blank=True, help_text='a, b, c, d, … oder leer für Kursstufe.', max_length=4, null=True, verbose_name='Klassen-Buchstabe')),
                ('curriculum_track', models.CharField(blank=True, choices=[('G8', 'G8'), ('G9', 'G9')], max_length=2, null=True, verbose_name='Schulzweig')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archiviert am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='lists.list', verbose_name='übergeordnete Liste')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lists', to='lists.listtemplate', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Liste',
                'verbose_name_plural': 'Listen',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ListRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Mitglied'), ('associate', 'Zugeordnet')], default='member', help_text='member: echtes Mitglied der Liste. associate: zugeordnet (z.B. Elternteil eines Kindes).', max_length=20, verbose_name='Rolle')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archiviert am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='lists.list', verbose_name='Liste')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='accounts.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Eintrag',
                'verbose_name_plural': 'Einträge',
                'unique_together': {('list', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ListAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('type', models.CharField(choices=[('text', 'Text'), ('email', 'E-Mail'), ('phone', 'Telefon'), ('number', 'Zahl'), ('choice', 'Auswahl'), ('checkbox', 'Häkchen'), ('user_relationship', 'Personen-Beziehung')], max_length=30, verbose_name='Typ')),
                ('must_be_public', models.BooleanField(default=False, help_text='Wenn gesetzt, kann der Eigentümer dieses Feld nicht verbergen.', verbose_name='muss öffentlich sein')),
                ('choices', models.JSONField(blank=True, default=list, help_text="Nur für Typ 'Auswahl': Liste der wählbaren Werte.", verbose_name='Auswahl-Werte')),
                ('choice_cap', models.PositiveIntegerField(blank=True, help_text="Nur für Typ 'Auswahl': Maximale Belegung pro Wert.", null=True, verbose_name='Auswahl-Kapazität')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='lists.listtemplate', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Listen-Attribut',
                'verbose_name_plural': 'Listen-Attribute',
                'ordering': ['position', 'id'],
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ListAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='lists.list', verbose_name='Liste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_of_lists', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Benutzergruppen-Mitgliedschaft',
                'verbose_name_plural': 'Benutzergruppe (Mitgliedschaften)',
                'unique_together': {('list', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ListAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='lists.list', verbose_name='Liste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_of_lists', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Listen-Admin',
                'verbose_name_plural': 'Listen-Admins',
                'unique_together': {('list', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ListRecordAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lists.listattribute', verbose_name='Attribut')),
                ('audience', models.ForeignKey(blank=True, help_text='Leer = öffentlich.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lists.list', verbose_name='Sichtbar für (Liste)')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='lists.listrecord', verbose_name='Eintrag')),
            ],
            options={
                'verbose_name': 'Eintrags-Sichtbarkeit',
                'verbose_name_plural': 'Eintrags-Sichtbarkeiten',
                'unique_together': {('record', 'attribute', 'audience')},
            },
        ),
        migrations.CreateModel(
            name='ListRecordValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='Wert (verschlüsselt)'))),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='lists.listattribute', verbose_name='Attribut')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='lists.listrecord', verbose_name='Eintrag')),
            ],
            options={
                'verbose_name': 'Eintrags-Wert',
                'verbose_name_plural': 'Eintrags-Werte',
                'unique_together': {('record', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ListSendPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('requires_release_click', models.BooleanField(default=False, verbose_name='Bestätigungs-Klick nötig')),
                ('transitive', models.BooleanField(default=False, help_text='Wenn true, gilt die Berechtigung auch für Unter-Listen der Ziel-Liste.', verbose_name='transitiv (auf Unter-Listen)')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_send_permissions', to=settings.AUTH_USER_MODEL, verbose_name='erteilt von')),
                ('granted_to_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_send_permissions', to='lists.list', verbose_name='berechtigte Liste')),
                ('target_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_send_permissions', to='lists.list', verbose_name='Ziel-Liste')),
            ],
            options={
                'verbose_name': 'Listen-Senderecht',
                'verbose_name_plural': 'Listen-Senderechte',
                'unique_together': {('target_list', 'granted_to_list')},
            },
        ),
        migrations.CreateModel(
            name='PersonRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Z.B. "Mutter von", "Vater von", "Erziehungsberechtigte von".', max_length=100, verbose_name='Rolle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_related', to='accounts.person', verbose_name='Person (Zugeordnet)')),
                ('subject_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_subject', to='accounts.person', verbose_name='Person (Mitglied)')),
            ],
            options={
                'verbose_name': 'Personen-Beziehung',
                'verbose_name_plural': 'Personen-Beziehungen',
                'unique_together': {('subject_person', 'related_person', 'role')},
            },
        ),
        migrations.CreateModel(
            name='RecordManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('creator', 'Ersteller'), ('invited', 'eingeladen'), ('guardian', 'Erziehungsberechtigte'), ('self_registered', 'selbst registriert')], max_length=20, verbose_name='Grundlage')),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='lists.listrecord', verbose_name='Eintrag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_records', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Eintrags-Verwalter',
                'verbose_name_plural': 'Eintrags-Verwalter',
                'unique_together': {('record', 'user')},
            },
        ),
    ]
